# Generated by Django 3.2.5 on 2021-07-24 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loft', '0002_loft_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='correct',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
