# Generated by Django 3.2.5 on 2021-07-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loft', '0004_auto_20210724_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='loft',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AddField(
            model_name='loft',
            name='amenities',
            field=models.ManyToManyField(related_name='apartments', to='loft.Amenity'),
        ),
    ]
