# Generated by Django 3.2.5 on 2021-07-24 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loft', '0005_auto_20210724_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='loft',
            name='long_description',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loft',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
