# Generated by Django 3.2.5 on 2021-07-24 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loft', '0006_auto_20210725_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loft',
            name='long_description',
            field=models.CharField(max_length=800),
        ),
    ]
