# Generated by Django 3.2.5 on 2021-07-24 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loft', '0007_alter_loft_long_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loft',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='apartments', to='loft.Amenity'),
        ),
    ]
